# see config options in https://github.com/vzhong/wrangl/wrangl/conf
defaults:
  - wrangl_supervised_experiment
  - _self_

##########
# training
##########
early_stopping:
    monitor: 'val_f1'
    mode: 'max'
optim:
  params:
    lr: 0.000001
gpus: 1
batch_size: 1
val_batch_size: 10
collate_fn: 'ignore'  # use 'ignore' to pass an identity collate and define featurize instead
max_steps: 1_000_000
log_every_n_steps: 10000
val_check_interval: 10000
val_sample_size: 100


##########
# naming
##########
model: 'binary'
project: 'mdmqma-final-classify-1'


###########
# params
###########
lm: '${oc.env:PWD}/dataset_construction/pretrained/bart-large'
num_processes: 1
max_context_length: 256
sample_size: 30
test_only: false
test_resume: 'last.ckpt'
limit_val_batches: 0.3
single_example_per_cluster: false
limit: false
